version: '3'
services:
  postgresql:
    image: postgres
    container_name: imba
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=imba
      - POSTGRES_PASSWORD=imba
      - POSTGRES_DATABASE=imba
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-imba
    ports:
      - '6379:6379'
